<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="<?php $_SERVER["DOCUMENT_ROOT"] ?> /styly/stylyvypisakci.css">

    </head>
    <body>

    <?php if ($this->data['session']['opravneni'] >= 1) : ?>
        <h1>Přidaní pozic pro sportovce</h1>

        <!-- Výpis zpráv -->
        <?php if (isset($this->zpravy) && !empty($this->zpravy)): ?>
            <ul>
                <?php foreach ($this->zpravy as $zprava): ?>
                    <li><?php echo $zprava; ?></li>
                <?php endforeach; ?>
            </ul>


        <?php endif; ?>
        <div class="container">
        <!-- Formulář pro přidání pozic -->
        <form  method="post">
            <label for="nazev_poz">Název pozice:</label>
            <input type="text" name="nazev_poz" required>
            <button type="submit" name="pridej">Přidat pozici</button>
        </form>
        </div>


        <!-- Výpis všech sportů -->

        <?php if (isset($this->data['poz']) && !empty($this->data['poz'])): ?>
            <h2>Všechny sporty</h2>
            <ul>
            <?php foreach ($this->data['poz'] as $poz): ?>
                <div class="container">
                    <h4><?php echo $poz['nazev_poz']; ?></h4>
                        <form method="post">
                            <input type="hidden" name="editovana_pozice_id" value="<?php echo $poz['id_poz']; ?>">
                            <label for="novy_nazev_pozice">Nový název pozice:</label>
                            <input type="text" name="novy_nazev_pozice" >
                            <button type="submit" name="ulozit">Uložit</button>
                            <input type="hidden" name="smazana_pozice_id" value="<?php echo $poz['id_poz']; ?>">
                            <button type="submit" name="smazat">Smazat</button>
                        </form>
                    </li>
                    </div>
                    <!-- Zde můžete přidat další informace o sportu, které chcete zobrazit -->
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>Nejsou k dispozici žádné pozice.</p>
        <?php endif; ?>

        <?php elseif($this->data['session']['opravneni'] === null) : $this->presmeruj("ldap"); 
        elseif($this->data['session']['opravneni'] === 0) : $this->presmeruj("uvod");
        endif ?>

    </body>
</html>