<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?php $_SERVER["DOCUMENT_ROOT"] ?> /styly/stylyvypisakci.css">
    <!-- Doplňte další obsah hlavičky zde -->
    <title>Uživatelský profil</title>
</head>

<body>


    <section class="zpravy">
        <?php if (isset($this->data['zpravy']) && is_array($this->data['zpravy'])) {
            foreach ($this->data['zpravy'] as $zprava) { ?>
                <div><?= $zprava ?></div>
            <?php }
        } ?>
    </section>
    <?php if ($this->data['session']['opravneni'] >= null) : ?>
    <main>
        <h1>Uživatelský profil</h1>
        <div class="container">       
            <?php if (isset($this->data['uzivatel']) || isset($this->data['sportovci'])) { ?>
                <?php $pole = array(); 
                if(isset($this->data['uzivatel'])){
                    foreach ($this->data['uzivatel'] as $key => $uzivatel) {
                        $pole[$key] = $uzivatel;
                    }
                }
                ?>

                <h4>Jméno:</h4>
                <p><?= $pole['jmeno'] ?></p>
                <h4>Příjmení:</h4>
                <p><?= $pole['prijmeni'] ?></p>
                <h4>Email:</h4>
                <p><?= $pole['email'] ?></p>
                <h4>Třída:</h4>
                <p><?= $pole['id_trid'] ?></p>
                <h4>Datum narození:</h4>
                <p><?= $pole['dat_nar'] ?></p>
                <h4>Pohlaví:</h4>
                <p><?= $pole['pohlavi'] ?></p>
                <h4>Kontaktní údaje:</h4>
                <p><?= $pole['kontaktni_udaje'] ?></p>
                <h4>Odkaz na webové stránky:</h4>
                <p><?= $pole['odkaz_na_web'] ?></p>
                <h4>Zdravotní omezení:</h4>
                <p><?= $pole['zdravotni_omezeni'] ?></p> 
                <div> 
                    <h4>Sportovní aktivity:</h4>
                    <?php 
                    foreach ($this->data['sportuje'] as $sportuje) {
                      if($pole['email'] != $sportuje['email']) {  
                        continue;
                      }
                        foreach ($this->data['discipliny'] as $disciplina) {
                            if ($disciplina['id_disc'] != $sportuje['id_disc']) {
                                continue;
                            }
                            echo "<h5>" . $disciplina['nazev_disc'] . "</h5>";
                         
                            // Vypsání příslušné úrovně
                            foreach ($this->data['uroven'] as $uroven) {
                                if ($uroven['id_urov'] == $sportuje['id_urov']) {
                                    echo "<p>Úroveň: " . $uroven['nazev_urov'] . "</p>";
                                    break;
                                }
                            }
                            // Vypsání příslušné pozice
                            foreach ($this->data['pozice'] as $pozice) {
                                if ($pozice['id_poz'] == $sportuje['id_poz']) {
                                    echo "<p>Pozice: " . $pozice['nazev_poz'] . "</p>";
                                    break;
                                }
                            }
                            // Přidání tlačítka pro odebrání sportu
                            ?>
                            <form method="post" action="">
                                <input type="hidden" name="odeber_sport" value="<?= $sportuje['id_sportuje'] ?>">
                                <button type="submit" name="odeber_sport_button">Odebrat sport</button>
                            </form>
                    <?php }
                      
                    } ?>
                </div>

                
            <?php } else { ?>
                <p>Uživatel není přihlášen nebo nebyl nalezen v LDAP.</p>
            <?php } ?>
        </div>

        <h2>Dodatečné informace</h2>
        <div class="container" >
            
        <?php if (isset($_SESSION['loggedIn']) && $_SESSION['loggedIn']) { ?>
            <form method="post" action="">
                <label for="kontaktni_udaje"><h3>Kontaktní údaje:</h3></label>
                <input type="text" name="kontaktni_udaje" value="<?= isset($this->data['uzivatel']['kontaktni_udaje']) ? $this->data['uzivatel']['kontaktni_udaje'] : '' ?>"><br>

                <label for="odkaz_na_web"><h3>Odkaz na webové stránky:</h3></label>
                <input type="text" name="odkaz_na_web" value="<?= isset($this->data['uzivatel']['odkaz_na_web']) ? $this->data['uzivatel']['odkaz_na_web'] : '' ?>"><br>

                <label for="zdravotni_omezeni"><h3>Zdravotní omezení:</h3></label>
                <input type="text" name="zdravotni_omezeni" value="<?= isset($this->data['uzivatel']['zdravotni_omezeni']) ? $this->data['uzivatel']['zdravotni_omezeni'] : '' ?>"><br>
                
                <!-- Skryté pole pro identifikaci uživatele -->
                <input type="hidden" name="uzivatel_id" value="<?= isset($this->data['uzivatel']['id_uziv']) ? $this->data['uzivatel']['id_uziv'] : '' ?>">

                <!-- Tlačítko pro uložení změn -->
                <input type="submit" name="ulozit_zmeny" value="Uložit změny">
            </form>




            
            <?php if (isset($_SESSION['loggedIn']) && $_SESSION['loggedIn'] && $session["opravneni"] < 1) { ?>
                <form method="post" action="">
                    <label for="sport"><h3>Sportovní aktivita:</h3></label>
                    <select name="sport" id="sport" class="custom-select">
                        <option value="" selected disabled>Vyberte disciplínu</option>
                        <?php foreach ($this->data['discipliny'] as $disciplina): ?>
                            <option value="<?= $disciplina['id_disc'] ?>"><?= $disciplina['nazev_disc'] ?></option>
                        <?php endforeach; ?>
                    </select>
                    
                    <select name="pozice" id="sport" class="custom-select">
                 <option value="" selected disabled>Vyberte pozici</option>
                    <?php foreach ($this->data['pozice'] as $pozice): ?>
                  <option value="<?= $pozice['id_poz'] ?>"><?= $pozice['nazev_poz'] ?></option>
             <?php endforeach; ?>
                </select>

                    <select name="uroven" id="sport" class="custom-select">
                        <option value="" selected disabled>Vyberte úroveň</option>
                        <?php foreach ($this->data['uroven'] as $uroven): ?>
                            <option value="<?= $uroven['id_urov'] ?>"><?= $uroven['nazev_urov'] ?></option>
                        <?php endforeach; ?>
                    </select>

                    <input type="submit" name="pridej_sport" value="Přidat sport">
                </form>
            <?php } ?>
        <?php } ?>
    </main>
    <?php elseif($this->data['session']['opravneni'] === null) : $this->presmeruj("ldap"); 
elseif($this->data['session']['opravneni'] === 0) : $this->presmeruj("uvod");
endif ?>


</body>
</html>

