<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Evidence sportovců</title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.2.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<?php $_SERVER["DOCUMENT_ROOT"] ?> /styly/stylyvypisakci.css">
 
</head>
<body>
    <!---header-->
   
    
<!---Nadpis na fotce-->
<section class="uvod">
        <div class="uvod-text">
            <h1>Evidence Sportovců</h1>
            <h2>Důvěřujte nám ve vaší cestě ke sportovnímu úspěchu</h2>    
        </div>
    </section>


	<section class="akce">
		
			<h1>Proč sportovat u nás?</h1>
		</div>
		<div class="akce-content">

			<!--SCHODY--->
			<div class="box"  >
				<img src="../fotky/stk.jpg">
				<h6>Turistické</h6>
				<h4>Kurzy</h4>
			</div>
			

			<!--KUCHYNE--->
			<div class="box"  >
				<img src="../fotky/adaptacnikurz.jpg">
				<h6>Adaptační</h6>
				<h4>Kurzy</h4>
			</div>
			

			<!--DVERE--->
			<div class="box">
				<img src="../fotky/lyzak.jpg">
				<h6>Lyžařské</h6>
				<h4>Kurzy</h4>
			</div>
			

			<!--OSTATNI--->
			<div class="box">
				<img src="../fotky/skolnisoutez.jpg">
				<h6>Školní</h6>
				<h4>Soutěže</h4>
			</div>
		</div>
	</section>





	<section class="footer">
        <div class="footer-box">
            <h3>Kontakt</h3>
            <a>l.hudecova@spseiostrava.cz</a><br>
            <a>j.hubacek@spseiostrava.cz</a><br>
            <a>d.kozakova@spseiostrava.cz</a>
        </div>
        <div class="footer-box">
            <h3>Střední průmyslová škola elektrotechniky a <br>informatiky Ostrava, příspěvková organizace</h3>
            <a>Telefon: 596 118 465</a><br>
            <a>E-mail: spsei@po-msk.cz5</a><br>
            <a>ID datové schránky: 89uxrcv</a><br>
            <a>Sokolská tř. 2689, 702 00 Moravská Ostrava a Přívoz</a>
        </div>
        <div class="footer-box">
            <h3>Sociální sítě</h3>
            <a href="https://www.facebook.com/SPSeiOstrava.cz"><i class="ri-facebook-fill"></i></a>
            <a href="https://www.instagram.com/spsei_ostrava/"><i class="ri-instagram-fill"></i></a>
        </div>
    </section>
    
</body>
</html>